{% set version = "1.0.1" %}
{% set build = 0 %}

package:
  name: tomocupy
  version: {{ version }}

source:
  url: https://github.com/tomography/tomocupy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9f57907a829a56495e5b9817f03905c72d13b336089cd623a270fb5027d9d997
build:
  skip: True  # [cuda_compiler_version != "11.2"]
  skip: True  # [cuda_compiler_version in (undefined, "None")]
  number: 0
  script: 
    - {{ PYTHON }} -m pip install . -vv [linux]    
  script_env:
    - CMAKE_GENERATOR=Ninja
  # Minimum supported arch of this package is 60
    - CUDAARCHS=60 
    #;72;75
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake
    - ninja [linux]
    - swig
  host:
#    - cudatoolkit  # [cuda_compiler_version != "None"]
    - numpy
    - pip
    - python
    - scikit-build
    - setuptools
  run:
    - python
#   - cupy
#   - h5py
#   - numexpr
#    - numpy
#    - opencv
#    - pywavelets
#    - tifffile

test:
   requires:
     - pip
   imports:
# Conda-forge bots do not have GPUs for testing
#      - tomocupy
   commands:
     - pip check
# Conda-forge bots do not have GPUs for testing
#      - tomocupy --help
     
about:
    home: https://github.com/tomography/tomocupy
    license: BSD-3-Clause
    license_family: BSD
    license_file: .licenses/license.c
    summary: 'GPU-based reconstruction of tomography data'
    
extra:
  recipe-maintainers:
    - nikitinvv
